CREATE TABLE `ck_mapper` (
  `mapname` varchar(54) NOT NULL,
  `mapper` varchar(64) DEFAULT 'N/A'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

INSERT INTO `ck_mapper` (`mapname`, `mapper`) VALUES
('surf_004_fix', 'MonkeyWithAGun'),
('surf_1234', 'Laxen'),
('surf_1dang', 'Who?'),
('surf_1day', 'Collaboration'),
('surf_1try', 'Jnnhfelix'),
('surf_2012_beta12', 'Collaboration'),
('surf_25_lighters', 'Big Blue'),
('surf_29palms', 'SkariZ^'),
('surf_2pacisalive', 'Umg_'),
('surf_3', 'Umg_'),
('surf_4dimensional', 'Streebree'),
('surf_4head_csgo', 'sjom7e'),
('surf_4steps', 'Kaneejn'),
('surf_6', 'Essence'),
('surf_666', 'Collaboration'),
('surf_81st_network_njv', 'Ryan Sterner '),
('surf_8bit', 'TaiiKii'),
('surf_a', 'Umg_'),
('surf_aaaa_reloaded', 'silverlol'),
('surf_aatsika', 'MOKKAMASTER'),
('surf_abstinens', 'Umg_'),
('surf_abstract_final', 'a-ha!'),
('surf_abyss_fix', 'Ninjaplz'),
('surf_acedia', 'Seynethic'),
('surf_acerbus', 'RazerSurf'),
('surf_acp_fix', 'Panzer'),
('surf_activation', 'iNooVa & biji'),
('surf_adrs', 'mr.aNa'),
('surf_adtr_njv', 'Ch!llers'),
('surf_advanced', 'b0at'),
('surf_adventure_easy', 'Gorange Ninja'),
('surf_adventure_final', 'Gorange Ninja'),
('surf_aeron', 'Ins'),
('surf_aether_csgo', 'Scaz.zaf'),
('surf_again_njv', 'Ch1!!3r'),
('surf_ag_texture_final', 'SmOoth'),
('surf_aircontrol_dark', 'N/A'),
('surf_aircontrol_ksf', 'SnoopSh'),
('surf_airflow', 'Enjooi'),
('surf_akai_f1n4l', 'akai'),
('surf_akai_final_fix', 'akai'),
('surf_alend', 'Ranth'),
('surf_alpha', 'Gorange Ninja'),
('surf_alpine', 'N/A'),
('surf_alternation', 'Ownd & Skyppy'),
('surf_amantiss_csgo', 'Mallow'),
('surf_amaranthine', 'Kuiq'),
('surf_amaro_fix', 'Flaudgin'),
('surf_amateur_v2b', 'Collaboration'),
('surf_ambient_fixed', 'Pimp Juice & Razer'),
('surf_ameliorate', 'granis'),
('surf_amir', 'Koga73'),
('surf_amplitude_encore', 'Buck Nasty'),
('surf_amplitude_encore_nsf_v4', 'Buck Nasty'),
('surf_amplitude_light', 'Buck Nasty'),
('surf_android', 'Xtra_Festive'),
('surf_andromeda', 'Syncronyze'),
('surf_and_destroy_fix', 'ZaLoS'),
('surf_angst_go', 'Proxychains'),
('surf_animals', 'Collaboration'),
('surf_animekoreanclgpeople', 'I_ken'),
('surf_annoyance_njv', 'svbg869'),
('surf_anoname', 'N/A'),
('surf_anonymity', 'Hiphopopotomus'),
('surf_anthropomorphic', 'Furchee'),
('surf_antimatter', 'Horsefeathers'),
('surf_antimatter_v2', 'Horsefeathers'),
('surf_antivero', 'Alice'),
('surf_anubis', 'Sneakyyy'),
('surf_anything', 'Phurix'),
('surf_anzchamps', 'Hardex'),
('surf_ape3', 'N/A'),
('surf_aphelion', 'Housegamer'),
('surf_apollonian', 'Collaboration'),
('surf_apollo', 'ApeXe'),
('surf_aquaflow', 'NvC_DmN_CH'),
('surf_aqua_fix', 'xRyanNitro'),
('surf_arcade', 'maz'),
('surf_ardon_fix', 'FPS God'),
('surf_arghmyeyes', 't3tra'),
('surf_arghmyeyes_retexture', 't3tra'),
('surf_artifex', 'Billy'),
('surf_aser', 'TruMatrix'),
('surf_ashpalt', 'N/A'),
('surf_aspiration', 'Cthulu'),
('surf_asrown', 'Escencia'),
('surf_astray', 'comrade teammate'),
('surf_ataque_final', 'Junior, G-Flow, Ryan_S'),
('surf_atlantis', 'Gorange Ninja'),
('surf_atlas_1', 'Val'),
('surf_atrium', 'ArcticPanda'),
('surf_at_the_limit_fixed', 'Gladeare'),
('surf_aura', 'ApeXe'),
('surf_aurantia-grisea', 'ChiChiN'),
('surf_auroia_njv', 'Escencia'),
('surf_auroria2', 'Escencia'),
('surf_autism', 'Titty Sprinkles'),
('surf_autism_2', 'Titty Sprinkles'),
('surf_aux', 'twistedVoid'),
('surf_awakening', 'Skyppy'),
('surf_aweles', 'Mazzo'),
('surf_aweles_inferno_fix', 'Koga73'),
('surf_ax', 'N/A'),
('surf_axil', 'Klemix'),
('surf_axiom2', 'krealington'),
('surf_axiom_fix', 'iNooVa'),
('surf_a_lot', 'Gladeare'),
('surf_a_tier_one_map', 'N/A'),
('surf_a_xblah_reborn', 'Xblah'),
('surf_bacalhau', 'Mastardy-1511 & ImHarker'),
('surf_bageena', 'Moonbearthegreat'),
('surf_banger', 'not_a_zombie & Joey'),
('surf_basalt', 'Veggissss'),
('surf_basic', 'N/A'),
('surf_bbb', 'Aux'),
('surf_before', 'Hardex'),
('surf_beginner', 'Kiiru'),
('surf_beginner2', 'Kiiru'),
('surf_beginner_h', 'N/A'),
('surf_beginner_hell_ksf', 'dotone'),
('surf_beginner_lin', 'Frumpy7'),
('surf_beginner_ug', 'N/A'),
('surf_believe_refix', 'OO SII'),
('surf_benevolent', 'Syncronyze'),
('surf_bepis', 'N/A'),
('surf_beverages', 'Sid'),
('surf_beverages_remix_go', 'Sid'),
('surf_bewatermyfriend', 'N/A'),
('surf_beyer', 'Juxtapo'),
('surf_beyer2', 'Juxtapo'),
('surf_beyond', 'granis & bro'),
('surf_be_gentle', 'Krealington'),
('surf_bigred_thing', 'Gibbay'),
('surf_biohazards', 'Kinder'),
('surf_blackandgold', 'Rated'),
('surf_blackheart', 'otter'),
('surf_blackout_v1', 'God Damnit Nappa'),
('surf_blackside_njv', 'Pupsik'),
('surf_bland', 'blandon'),
('surf_blub_njv', 'Chayma'),
('surf_blue', 'blueiv'),
('surf_bluesky_beta', 'Gorange_Ninja'),
('surf_bluewall', 'Biji'),
('surf_bluewinter_final', 'iamsupaman'),
('surf_blurry_fix', 'N/A'),
('surf_blyad', ' Nimbus'),
('surf_boatastic', 'Pattermayn'),
('surf_bob', 'ptad'),
('surf_boboken', 'Storzenbecher'),
('surf_bombix_v2', 'boomix'),
('surf_boneless_beta', 'N/A'),
('surf_boner', 'BonerForest'),
('surf_bonk', 'N/A'),
('surf_bonkers_v2', 'The Frying Dutch Pan'),
('surf_bonus', 'Gorange_Ninja'),
('surf_borderlands', 'Wall-E'),
('surf_borderlands_h', 'wiuuuh'),
('surf_boreas', 'Syncronyze'),
('surf_boring', 'Collaboration'),
('surf_bork_nbv', 'Rambjoe & Kiiru'),
('surf_botisses', 'Schranz'),
('surf_boy_fixed', 'SkariZ'),
('surf_braininvasion', 'Kiiru & OwndD'),
('surf_brake1000', 'N/A'),
('surf_bricks', '	Rock'),
('surf_brickwood', 'ciaHo'),
('surf_brodderlands', 'Flow, Proxychains, TheFur'),
('surf_broken', 'b0at'),
('surf_brutalist', 'Hardex'),
('surf_brutalist_ez', 'Hardex'),
('surf_buffer', 'Buffer'),
('surf_bullet_csgo', 'Collaboration'),
('surf_bumpybusride', 'Hardex'),
('surf_burga_alpha1', 'meso420'),
('surf_b_r_o_x_x_x', 'AmstaFF & Spider'),
('surf_caca', 'Swaaaaag'),
('surf_caesart', 'N/A'),
('surf_caged', 'HammY'),
('surf_calamity2', 'SacRed'),
('surf_calamity_njv', 'SacRed'),
('surf_calibration', 'SacRed'),
('surf_calycate2', 'ArcticPanda'),
('surf_calycate_ksf', 'ArcticPanda'),
('surf_calzone', 'sh_bro, Krealington, mr.25'),
('surf_cancer', 'James'),
('surf_candyland', 'JohnnyBoy'),
('surf_canisius2', 'Billy'),
('surf_canisius2_fix', 'Billy'),
('surf_cannonball', 'EICHHOERNCHEN'),
('surf_carnage', 'Googee'),
('surf_cartoon', 'Gorange-Ninja'),
('surf_casbah_fix', 'Comrade Teammate'),
('surf_castlewalls', 'Gorange-Ninja'),
('surf_castle_final', 'N/A'),
('surf_cat', 'N/A'),
('surf_catalyst', 'Copy-Mark'),
('surf_catalyst2', 'Razer & Billy'),
('surf_cave', 'Oatneil'),
('surf_cavemissile_fix', 'EICHHOERNCHEN'),
('surf_cawsmic', 'N/A'),
('surf_celestial', 'Sunday'),
('surf_cement', 'N/A'),
('surf_chaos_refix', 'LEO'),
('surf_chasm_go', 'SID'),
('surf_chateau_fix', 'Hesuka'),
('surf_chill', 'Dimitri'),
('surf_christmas2_fix', 'Collaboration'),
('surf_christmas_fix', 'Collaboration'),
('surf_cinnamon_fix', 'wayne3288'),
('surf_citadelcbackup', '09420669'),
('surf_classics', 'Panzer'),
('surf_classics2', 'Panzer'),
('surf_classics3', 'Collaboration'),
('surf_clavius', 'Horsefeathers'),
('surf_clockwork', 'Helix'),
('surf_clujreek', 'SkariZ^'),
('surf_coblazt', 'N/A'),
('surf_collaboration', 'Grueddi & Chuck Norris'),
('surf_collection_njv', 'Pand3mic & Baxter'),
('surf_colmixv2_aqr', 'Aqresiv3'),
('surf_colored_challenge', 'N/A'),
('surf_colors2_beta', 'N/A'),
('surf_colors_beta1', 'N/A'),
('surf_colors_final', 'N/A'),
('surf_color_njv', 'Collaboration'),
('surf_colours', 'Zombiesquatch'),
('surf_colum', 'JohnnyOuh'),
('surf_colum_2', 'Wiuuuh'),
('surf_colum_again', 'Wiuuuh'),
('surf_colum_up', 'FörsterPvP'),
('surf_commune_again_beta5', 'Unknown'),
('surf_commune_beta11', 'Unknown'),
('surf_commune_too_beta5', 'Collaboration'),
('surf_compact', 'Billy'),
('surf_compulsive_h', 'razEr'),
('surf_compulsive_njv_fix', 'RazerSurf'),
('surf_concept_njv', 'Grueddi'),
('surf_concreteideas', 'SmileyTopin'),
('surf_concretejungle_fix', 'PretzL & Hesuka'),
('surf_concrete_workshop', 'N/A'),
('surf_conserve', 'Wackywallaby'),
('surf_consistenza_diversa', 'Wakthor Thorwak'),
('surf_constrictor_remix', 'Sid'),
('surf_construction', 'CopyMark'),
('surf_cookiejar', 'Kiiru'),
('surf_coralis_ksf', 'Escencia'),
('surf_cordelia', 'RazerSurf'),
('surf_core_fix', 'Collaboration'),
('surf_corner', 'Slickytail'),
('surf_corporal', 'Yyoda'),
('surf_corruption', 'Oli'),
('surf_cosmic', 'TheCosmicWolf'),
('surf_cosmo', 'Rathe'),
('surf_cosmo_workshop', 'Storzenbecher'),
('surf_cozy', 'Mr. Cow'),
('surf_crackdesert_evo2', 'Housegamer'),
('surf_crajjie', 'N/A'),
('surf_creation', 'Collaboration'),
('surf_crimson', 'Geoff'),
('surf_crownroyal', 'a-ha!'),
('surf_crush', 'Xtra_Festive'),
('surf_crush2', 'Xtra'),
('surf_crystal', 'Copy-Mark'),
('surf_crzyfrog_reloaded_fix', 'JackTheStripper'),
('surf_cubic', 'Scaz.zaf'),
('surf_curan', 'Zeta'),
('surf_curious', 'Lightning'),
('surf_cyanide_njv', 'Diealready'),
('surf_cyberwave_fix', 'Mr. Cow'),
('surf_cyka_ksf', 'Umg_'),
('surf_damn', 'Biji'),
('surf_damnub2', 'DamNub'),
('surf_dank', ':D'),
('surf_dark_v1', 'Jackmister'),
('surf_dawn', 'Mashau'),
('surf_deadline', 'House'),
('surf_deathstar', 'Downycat'),
('surf_death_of_a_martian', 'Gorange_Ninja'),
('surf_deceptive_final', 'razEr'),
('surf_decked', 'N/A'),
('surf_deeper', 'Sjup'),
('surf_deeznuts', 'Trout'),
('surf_defectum', 'N/A'),
('surf_delight_go', 'Aqresiv3'),
('surf_delta', 'Sense & krealington'),
('surf_delusional', 'SKAR'),
('surf_deoa', 'Deod'),
('surf_deod_beta', 'Deod'),
('surf_deprecation', 'not_a_zombie'),
('surf_depressing', 'Serz'),
('surf_depths', 'Streebree'),
('surf_deroland_neon_final', 'Baldur'),
('surf_derpis_h_fix', 'Diealready'),
('surf_derpis_ksf', 'Diealready'),
('surf_deserted_njv', '.:PROTOTYPE:.'),
('surf_desert_final', 'N/A'),
('surf_desolate', 'Juxtapo'),
('surf_despair_x14', 'N/A'),
('surf_destiny_fixed', 'Codowner'),
('surf_detroit', 'Stratus1G'),
('surf_developer_begginer', 'Skymaster'),
('surf_devil', 'Collaboration'),
('surf_dhyana', '^smiley'),
('surf_diamond_beta1', 'Raptor '),
('surf_diar', 'N/A'),
('surf_digital[g]beta_fixed', 'X-shark'),
('surf_diminsion', 'MonkeyWithAGun'),
('surf_dinwod', 'Dinwod356'),
('surf_dionysus', 'LightninG '),
('surf_disaster', 'Mr.25'),
('surf_discovery_njv', 'Billy'),
('surf_disco_extreme', 'N/A'),
('surf_disneyland', 'Collaboration'),
('surf_distraction_v2', 'Sacred'),
('surf_diverge', 'Kiiru'),
('surf_divided_nsf', 'Skyppy'),
('surf_dogs', 'N/A'),
('surf_domain', 'Sid'),
('surf_doodles_njv', 'Doodles'),
('surf_dova', 'Hork'),
('surf_dragon', 'yoghurt'),
('surf_drain', 'Jaden'),
('surf_dread', 'Mr. Mackey'),
('surf_dream', 'Mumble98'),
('surf_dreams', 'Shynex/Vay'),
('surf_drifting_go', 'murglegurgle'),
('surf_driftless_go', 'murglegurgle'),
('surf_drift_go', 'murglegurgle'),
('surf_drugs_csgo', 'Bonjorno7'),
('surf_duggywuggy', 'Douglas Rattman'),
('surf_dusk', 'Mr. Cow'),
('surf_dynamics_fixed', 'Blaine'),
('surf_dynasty', 'Scaz.zaf'),
('surf_easier_than_easy', 'N/A'),
('surf_easiest_map_ever', 'Phatboyjawsh'),
('surf_easy', 'N/A'),
('surf_easy1', 'KristiánP'),
('surf_easy2', 'KristiánP'),
('surf_easymap', 'N/A'),
('surf_ebob4', 'Zhelle & Bombu1V9'),
('surf_ebony', 'Big Sid'),
('surf_eclipse_fix', 'Paper-Cut'),
('surf_ecosystem', 'Silverlol'),
('surf_edge', 'fr3shz'),
('surf_efficacy_rg', 'MvRouC12'),
('surf_eggplant', 'HammY'),
('surf_egypt2', 'Mariowned'),
('surf_egypt_csgo', 'Umg_'),
('surf_eldritch', 'a-ha!'),
('surf_elements_beta3_fix', 'Ryan S'),
('surf_elites_v2', 'Svbg869'),
('surf_elites_v2_fix', 'Svbg869'),
('surf_elsurfo', 'N/A'),
('surf_elysium', 'Sacred'),
('surf_elysium2', 'Sacred'),
('surf_elysium3', 'Sacred'),
('surf_elysium4', 'Sacred'),
('surf_ember2', 'Hardex'),
('surf_ember_sns', 'SKAR'),
('surf_endurci', 'Oui'),
('surf_enlightened', 'Benchmarked'),
('surf_entropy_finalv2', 'Gorgeous Gentleman'),
('surf_entropy_hardmode', 'Gorgeous Gentleman'),
('surf_eon', 'Sense'),
('surf_epithet', 'BlueRaven'),
('surf_eryr', 'RNC1839'),
('surf_eryr2', 'RNC1839'),
('surf_escape_final', 'HammY'),
('surf_essentia', 'TopHATTwaffle'),
('surf_eternal_beta', 'Panzer'),
('surf_ethereal', 'Collaboration'),
('surf_eunoia', 'krealington'),
('surf_euphoria', 'Billy'),
('surf_eventide', 'Mariowned'),
('surf_exclave', 'Malt'),
('surf_execute', 'Vivio'),
('surf_exile_njv', 'Pyanih Ezhik'),
('surf_exland', 'Bontar0'),
('surf_exocube', 'Pyanih Ezhik'),
('surf_exocube_e', 'Pyanih Ezhik'),
('surf_exocube_h', 'Pyanih Ezhik'),
('surf_exogenesis', 'Pyanih Ezhik'),
('surf_exonic', 'Roz'),
('surf_explorer', 'Noobre'),
('surf_extremex', 'Tioga060'),
('surf_extremex2_5_njv', 'Tioga060'),
('surf_extrodinaire', 'Hiphopopotomus'),
('surf_exurbia_v2', 'ArcticPanda'),
('surf_exxak', 'Nemix'),
('surf_exxe', 'Exxelence'),
('surf_ez', 'Entonic'),
('surf_ez3', 'Waj'),
('surf_ezclap', 'Sjom7e'),
('surf_ezpz_fifiedition', 'N/A'),
('surf_ezpz_GFL', 'N/A'),
('surf_ezpz_syntax', 'lmaosyntax'),
('surf_ezsurf', 'N/A'),
('surf_ez_surf_2', 'N/A'),
('surf_fabas', 'MaKo & Roxy'),
('surf_faceless', 'DownyCat'),
('surf_facility', 'krealington'),
('surf_fade', 'FriendlyChemist'),
('surf_faint_fix', 'Kippe'),
('surf_fantasy', 'Maz64'),
('surf_fast', 'Panzer'),
('surf_fathom', 'N/A'),
('surf_feudal', 'Mrdeadguy34'),
('surf_fever', 'N/A'),
('surf_fiellu', 'Kahvo'),
('surf_fightems', 'Cobblestoned'),
('surf_fijy', 'Fijy'),
('surf_finesse_final', 'Collaboration'),
('surf_fire_eye', 'Recoil'),
('surf_first', 'Wiuuuh'),
('surf_fish_njv', 'GamÂ£m0nKÂ£Y'),
('surf_flamingo', 'I_ken'),
('surf_flappybird', 'SyFo'),
('surf_flatliners', 'Aux'),
('surf_flipv2_go', 'Flip'),
('surf_flixy', 'N/A'),
('surf_flow', 'Koga73'),
('surf_flow_a', 'Koga73'),
('surf_flyingcastle_fixv2', 'N/A'),
('surf_flyin_fortress', 'HellRaisedSurfer'),
('surf_fomsey', 'N/A'),
('surf_forbidden_swag', 'Umg_'),
('surf_forbidden_tomb', 'Rapsodia'),
('surf_forbidden_tomb2', 'Rapsodia'),
('surf_forbidden_tomb2_njv', 'Rapsodia'),
('surf_forbidden_tomb3', 'Rapsodia'),
('surf_forbidden_tomb4_njv', 'Rapsodia'),
('surf_forbidden_tomb_sns', 'RiddlerAJ'),
('surf_forbidden_ways_ksf', 'Krusty'),
('surf_ford', 'Natanskybudder8'),
('surf_forgotten', 'Biji'),
('surf_forgotten_fix', 'Biji'),
('surf_forkentofixplz', 'N/A'),
('surf_fornax', 'iNooVa'),
('surf_fortress', 'Collaboration'),
('surf_fortum', 'Collaboration'),
('surf_for_all', 'Enjooi'),
('surf_for_noob', 'NoxXious'),
('surf_four_elements', '^Dede'),
('surf_fractal', 'Kingkurtis'),
('surf_freaky_njv', 'Freaky456'),
('surf_freedom', 'notSmashed'),
('surf_frequency_njv', 'NoPro'),
('surf_frey', 'KappaEliitti'),
('surf_frey2_go_fix', 'KappaEliitti'),
('surf_frey2_ksfgo', 'KappaEliitti'),
('surf_frey_remake_go', 'KappaEliitti'),
('surf_friday', 'iamsupaman'),
('surf_froots_ksf', 'Collaboration'),
('surf_frost', 'Xtra_Festive'),
('surf_froyo', 'Co1or'),
('surf_fruits2', 'Collaboration'),
('surf_fruits_fix', 'Collaboration'),
('surf_frus', 'Kozaa'),
('surf_frustration', 'SONICSOUR'),
('surf_fs', 'N/A'),
('surf_fuckyou', 'Wayne3288'),
('surf_fun', 'GroundSnake'),
('surf_fungus', 'MaKo'),
('surf_funhouse2', 'KrakenDaddy'),
('surf_funhouse_fix', '[UDel]Steve'),
('surf_furios', 'Chefkochmaps'),
('surf_fusion_final', 'Semikiller'),
('surf_fusubi', 'Bontar0'),
('surf_gaap', 'N/A'),
('surf_galactic_zts', 'Downycat'),
('surf_garden_go', 'Big Sid'),
('surf_garden_h_go', 'Big Sid'),
('surf_gauntlet_final', 'HellRaisedSurfer'),
('surf_gc_liberdade', 'N/A'),
('surf_gekar', 'caaz'),
('surf_gekyume_circumcision', 'a-ha!'),
('surf_generic', 'Bicuits'),
('surf_germania', 'Collaboration'),
('surf_gettingharder', 'das_d!'),
('surf_gforce', 'N/A'),
('surf_ghost_busters', 'Collaboration'),
('surf_giantmap', 'N/A'),
('surf_gisela_eich', 'N/A'),
('surf_glamour', 'Hergs'),
('surf_glass10', 'Exfib0'),
('surf_glass20', 'Swaaaaag'),
('surf_glass5', 'Smileytopin'),
('surf_glass7', 'Smileytopin'),
('surf_glass9', 'Smileytopin'),
('surf_gleam', 'TruMatrix'),
('surf_gleam2', 'TruMatrix'),
('surf_glitch-shortversion', 'DragonHeart000'),
('surf_globalchaos', 'LiNus'),
('surf_gloomy', 'krakenDaddy'),
('surf_gloom_njv', 'Ryan S'),
('surf_glorious', 'MrCloudyMan'),
('surf_glw', 'Glow_er'),
('surf_goat_fix', 'Xtra_Festive'),
('surf_gold1', 'Kaneejn'),
('surf_goldarn', 'FalseLogic'),
('surf_golden_fix', 'Koga73'),
('surf_goliath', 'Hardex'),
('surf_goodbye2', 'Hulda'),
('surf_gradient', 'Hippy'),
('surf_graphia', 'Target Practice'),
('surf_grassland', 'XShark'),
('surf_grayscale', '64mb'),
('surf_greenbrick', 'TempSo'),
('surf_greenday', 'Gere'),
('surf_greenhouse', 'Sagan'),
('surf_greensway', 'NvC_DmN_CH'),
('surf_grid', 'Gorange Ninja'),
('surf_grotta', 'Forki'),
('surf_grotto', 'Xtra_Festive'),
('surf_grunz', 'Natanskybudder8'),
('surf_gudrun', 'SkariZ^'),
('surf_guitar_hi', 'Masog'),
('surf_gurus_njv', 'Collaboration'),
('surf_hades', 'ArcticPanda'),
('surf_hades2', 'ArcticPanda'),
('surf_half_baked', '^smiley'),
('surf_halloween', 'Collaboration'),
('surf_halloween_tf', 'Egan'),
('surf_happyhands', 'Kiiru'),
('surf_happyhands2', 'Kiiru'),
('surf_happyhands3', 'Kiiru'),
('surf_happyhands4', 'Kiiru'),
('surf_happyhands5', 'Kiiru'),
('surf_happyhands_test', 'Kiiru'),
('surf_happyhug', 'Collaboration'),
('surf_harmony', 'PrisonNightmare'),
('surf_hat', 'Dexter'),
('surf_havaku_b1', 'SenseiFin'),
('surf_haze', 'npb'),
('surf_healthy_e', 'Collaboration'),
('surf_hearth_fix', 'GoZynth'),
('surf_heaven', 'Collaboration'),
('surf_heftig', 'Turbo'),
('surf_hekkz', 'Midahekki'),
('surf_hektik', 'Fizu'),
('surf_helium_v2_rg', 'Waffleburger'),
('surf_helloworld', 'Fatfuk'),
('surf_hentai', 'iiTzSheooo & ziomekYOYO'),
('surf_hero', 'N/A'),
('surf_hero_go', 'Biji'),
('surf_het', 'SkariZ^'),
('surf_highlands', 'ArcticPanda'),
('surf_hilirium_2017', 'N/A'),
('surf_hob', 'Syncronyze'),
('surf_hobo', 'JumpingHobo3'),
('surf_holiday_fix', 'iNooVa'),
('surf_hollow', 'Vampiricx & Xtra_Festive'),
('surf_honker_rg', 'Tick-Tock'),
('surf_hope', 'Collaboration'),
('surf_hopi_caged_v1', 'Cpt. Hopi'),
('surf_hopi_easy', 'Cpt. Hopi'),
('surf_hopi_gradient_v1', 'Cpt. Hopi'),
('surf_horizon_njv', 'Kompile'),
('surf_hotrod', 'FriendlyChemist'),
('surf_hotrod_beta', 'FriendlyChemist'),
('surf_hotwheels', 'Hardex'),
('surf_hourglass', 'Masog'),
('surf_how2surf', 'Masog'),
('surf_hoy', 'Addio'),
('surf_hoy_crazyideas', 'Addio'),
('surf_hoy_someideas', 'Addio'),
('surf_huntworking', 'N/A'),
('surf_hunty', 'Rex'),
('surf_hurrr', 'SKAR'),
('surf_hydrogen_v2', 'Waffleburger, Knife, & Icecreamlock'),
('surf_hyper', 'Helix'),
('surf_iamsupaman_beta1', 'Iamsupaman'),
('surf_icetest', 'Ice & 2CAN'),
('surf_iceworld', 'Ins'),
('surf_idn', 'iodaN^'),
('surf_illumination', 'Doink Face'),
('surf_illumination2', 'Doink Face'),
('surf_illusory', 'N/A'),
('surf_illusion', 'Juxtapo, Syncronyze, maz & Phurix'),
('surf_imagine_fix', 'THAY-imagine'),
('surf_imex_njv', 'Junior'),
('surf_iminyourbasement', 'Buffer'),
('surf_immortal_01', 'N/A'),
('surf_immortal_02', 'N/A'),
('surf_impact_njv', 'Sangre'),
('surf_impact_tnn', 'ItzGallows'),
('surf_industries_njv', 'Razersurf'),
('surf_infamous_ksf', 'Collaboration'),
('surf_infected_h', 'Hulda'),
('surf_infected_njv', 'Hulda'),
('surf_inferno', 'Syko_'),
('surf_ing_njv', 'RambJoe'),
('surf_inhuman', 'Noztic'),
('surf_injection_njv', 'Exither'),
('surf_injustice', 'Presumed Dead'),
('surf_inner', 'Klemix'),
('surf_innokia', 'Hesuka'),
('surf_inrage', 'Ch!ll3r'),
('surf_inrage2', 'Ch!ll3r'),
('surf_insanity', 'N/A'),
('surf_insanity2', 'N/A'),
('surf_insideout_final', 'Enjooi'),
('surf_insignia_b1', 'LiNus'),
('surf_inspire', 'Ins'),
('surf_intense', 'Essence'),
('surf_interceptor', 'Razersurf'),
('surf_interference_csgo', 'NvC_DmN_CH'),
('surf_intothewild', 'Koga73'),
('surf_intra', 'Maz64'),
('surf_in_space_go', 'KappaEliitti'),
('surf_in_the_dark', 'Drk_KZG'),
('surf_iridium', 'N/A'),
('surf_island', 'Scaz.zaf'),
('surf_itcannotbeeasier', 'PaiN'),
('surf_it_straight', '♥stxphxn♥'),
('surf_ivo', 'xVivio'),
('surf_ivory', 'Sid'),
('surf_ixtab_njv', 'Sacred'),
('surf_izded', 'Mr.25'),
('surf_jail_go', 'Murglegurgle'),
('surf_jakdum', 'JathOsh'),
('surf_jaqen', 'Hardex'),
('surf_jaqen2', 'Hardex'),
('surf_jash440', 'Jash440'),
('surf_jeff', 'Garanimal'),
('surf_jenocide', 'Jongent123'),
('surf_jizznipples', 'N/A'),
('surf_joshog_final', 'King of the Bananas'),
('surf_journeys_final', 'razersurf'),
('surf_juhis', 'Juhis'),
('surf_jumble', 'Xtra_Festive'),
('surf_jump', 'N/A'),
('surf_junglespic_ksf', 'Juxtapo'),
('surf_jusched', 'notSmashed'),
('surf_juturna', 'ashm0re'),
('surf_juturna_easy', 'ashm0re'),
('surf_kaboom', 'D- Pickles'),
('surf_kairo', 'PretzL'),
('surf_kaladin', 'F1nister'),
('surf_kalium', 'N/A'),
('surf_kalium2', 'Helix'),
('surf_katyna_a', 'N/A'),
('surf_kawaii', 'Nikki Nueva'),
('surf_kepler', 'FriendlyChemist'),
('surf_kimetrik', 'Lovhon'),
('surf_kinetic', 'Mumble98'),
('surf_kingdom_v1', 'N/A'),
('surf_kinshi', 'Seenko'),
('surf_kitsune', 'Arblarg'),
('surf_kitsune2_beta', 'Arblarg'),
('surf_kitsune2_GO', 'Arblarg'),
('surf_kitsune_nb', 'Arblarg'),
('surf_kloakk', 'PretzL'),
('surf_klue', 'Klemix'),
('surf_koa', 'TeMP'),
('surf_korn', 'Payn'),
('surf_krow10', 'Exither'),
('surf_kuaga', 'N/A'),
('surf_kultur', 'Sonia'),
('surf_kyuubi', 'Kyuubi'),
('surf_kz_mix_journeys', 'SoUlFaThEr'),
('surf_kz_protraining', 'SoUlFaThEr'),
('surf_lab', 'TECH'),
('surf_lament_njv', 'God Damnit Nappa'),
('surf_lamppost', 'Incredirocks'),
('surf_larry', 'N/A'),
('surf_lavaflow', 'Kiiru'),
('surf_lax_fix', 'Krealington'),
('surf_leafy', 'Sugartitty'),
('surf_lechumap', 'Fran'),
('surf_leesriize', 'Leesriize'),
('surf_leet_xl_beta7z', 'N/A'),
('surf_leet_xl_r12', 'N/A'),
('surf_legendary', 'Collaboration'),
('surf_legends', 'SintaxError'),
('surf_legends_lite', 'SintaxError'),
('surf_lepidus', 'Tilt'),
('surf_lesa', 'N/A'),
('surf_lessons', 'Helix'),
('surf_lianfora', 'Ins'),
('surf_liberation', 'MachINE'),
('surf_liberation2', 'MachINE'),
('surf_libya', 'b0at'),
('surf_lies', 'Umg_'),
('surf_lies_ksf', 'Umg_'),
('surf_life_of_cow', 'Krealington'),
('surf_life_of_doc', 'SKAR'),
('surf_life_of_duck', 'SKAR'),
('surf_life_of_duck_go', 'SKAR'),
('surf_lighrust_easy', 'Sheogorath'),
('surf_lighthouse', 'Ins'),
('surf_lightstones_light', 'NOiDeasStudio'),
('surf_like_this', 'Koga73'),
('surf_lilorm', 'N/A'),
('surf_limbo_go', 'murglegurgle'),
('surf_linear5', 'N/A'),
('surf_liopleurodon2', 'Magical Liopleurodon'),
('surf_liopleurodon_final', 'Magical Liopleurodon'),
('surf_lithium', 'Copy-Mark'),
('surf_lithium2', 'Copy-Mark'),
('surf_lockdown', 'Pedroknz'),
('surf_loentra', 'Ins'),
('surf_loentra_easy', 'Ins'),
('surf_lolrevlis', 'Silverlol'),
('surf_lolrevlis2', 'Silverlol'),
('surf_lolwhut', 'CyaN1de^'),
('surf_lonnaly', 'LonnaKinns'),
('surf_looksmodern', 'Tioga060'),
('surf_lore_e', 'Target Practice'),
('surf_lore_fix', 'Target Practice'),
('surf_lost', 'Flux'),
('surf_lost2', 'Flux'),
('surf_love', 'Collaboration'),
('surf_loveland', '♥stxphxn♥'),
('surf_loves_spliff', '[frank.]'),
('surf_lovetunnel', 'Maz64'),
('surf_lovhon', 'Lovhon'),
('surf_loweffort', 'Vay'),
('surf_low_production', 'Mr. Cow'),
('surf_lowestbidder', 'N/A'),
('surf_lo_tek', 'Axel'),
('surf_lt_omnific_fix', 'Nyro'),
('surf_lt_unicorn_official', 'Nyro'),
('surf_lullaby_ksf', 'God Damnit Nappa'),
('surf_lullaby_redone_njv', 'Wiuuuh'),
('surf_luminaris', 'KappaEliitti'),
('surf_lush', 'Rathe'),
('surf_lux', 'SSStormy'),
('surf_luxus_csgo', 'Luxus'),
('surf_mackful', 'VenusOG'),
('surf_magic', 'N/A'),
('surf_magma', 'daddy oSee'),
('surf_maip_4_beta1', 'N/A'),
('surf_major_dark', 'N/A'),
('surf_mao', 'Mibes'),
('surf_map', 'Pand3mic'),
('surf_map_h', 'Pand3mic'),
('surf_marah', 'Flaudgin'),
('surf_marbleblast_e', 'BlueRaven'),
('surf_marble_first', 'Zatura24'),
('surf_marton', 'Martons'),
('surf_mash-up', 'Collaboration'),
('surf_masonry', 'Mr. Cow'),
('surf_master', 'Xzippyzachx'),
('surf_master2', 'Xzippyzachx'),
('surf_mastering', 'Jurandir'),
('surf_mate', 'Edy'),
('surf_maxcant', 'Pablo'),
('surf_mdrn', 'Syncronyze'),
('surf_me', 'Not_a_zombie'),
('surf_megaeasy', 'DotzGOD'),
('surf_mejai', '4Shot Fanboy'),
('surf_mellow', 'Rezonate'),
('surf_meme', 'Collaboration'),
('surf_memoria', 'Thursday'),
('surf_memories', 'Chrissybear'),
('surf_mephobia_final', 'Yeri'),
('surf_meridional', 'N/A'),
('surf_mesa', 'Arblarg'),
('surf_mesa_aether_fix', 'Arblarg'),
('surf_mesa_fix', 'N/A'),
('surf_mesa_mine_fix', 'Arblarg'),
('surf_mesa_revo_go', 'Arblarg'),
('surf_mestro_ez', 'N/A'),
('surf_metallic', 'Mr. Cow'),
('surf_metalwall', 'Hulda'),
('surf_methadone', 'Ins'),
('surf_method', 'N/A'),
('surf_methone', 'Methone & Natanskybudder8'),
('surf_midsommar', 'Granis'),
('surf_milkyway', 'Mr. Cow'),
('surf_minecraft', 'b0at'),
('surf_minecraft_2016_final', 'MaverickBg'),
('surf_minecraft_2020_fix', 'Koga73'),
('surf_minesport', 'Ale'),
('surf_minigolf', 'Xbmann'),
('surf_minimumwage', 'Serz'),
('surf_minuet_njv', 'God Damnit Nappa'),
('surf_miracle', 'Mazzo'),
('surf_mirrors', 'Juhis'),
('surf_misc', 'FreakOut'),
('surf_mislorm', 'N/A'),
('surf_missing_no', 'Ryan S.'),
('surf_misty', 'FIREK'),
('surf_mjk', 'Gladeare'),
('surf_mokuzai', 'Oscar'),
('surf_molstration', 'Lody'),
('surf_mom', 'Xtra_Festive'),
('surf_mom_fix', 'Xtra_Festive'),
('surf_monochrome', 'Minimalis'),
('surf_monolith', 'Gorange Ninja'),
('surf_monotony', 'Collaboration'),
('surf_monsterguts', 'Papa Panda Yo!'),
('surf_moonkingdom', 'JD!'),
('surf_morbid', 'Sacred'),
('surf_motion1', 'Masog'),
('surf_motion1_easy', 'Masog'),
('surf_mudkip_fix', 'RNC1839'),
('surf_murmenia1stage1test', 'Murmen'),
('surf_mushroom_ksf', 'Chefkochmaps'),
('surf_mwag_reloaded', 'Monkeywithagun'),
('surf_mynah_final', 'Nikki Nueva'),
('surf_my_shit', 'APirateTurtle'),
('surf_nac', 'Big Blue'),
('surf_nascent_csgo', 'Whimsy'),
('surf_natura', 'Crystal'),
('surf_nature', 'Jemix'),
('surf_nebula', 'iNooVa'),
('surf_nemesis', 'Sacred'),
('surf_neon2', 'N/A'),
('surf_neon_beta', 'N/A'),
('surf_neon_final', 'Ch1!!3r'),
('surf_neoplasma', 'Kujoen'),
('surf_neoteric', 'Sam'),
('surf_neo_njv', 'N/A'),
('surf_neptune', 'N/A'),
('surf_nesquik', 'Sam'),
('surf_networked', 'Ryan S.'),
('surf_network_2008_final', 'Ryan S'),
('surf_network_2009_njv', 'Ryan S'),
('surf_network_2013', 'Ryan S'),
('surf_new', 'Horizon'),
('surf_newbie', 'NOiDeasStudio & Sheogorath'),
('surf_newb_hazard_r1', 'N/A'),
('surf_nexus', 'N/A'),
('surf_neyon', 'Mike'),
('surf_night', 'Magical Liopleurodon'),
('surf_nightmare', 'Collaboration'),
('surf_nikolo', 'Lucky Charms'),
('surf_ninja_go_b5', 'Drunken Ninja & Mario'),
('surf_ninja_r4', 'Drunken Ninja & Mario'),
('surf_nitro', 'xRyanNitro'),
('surf_noble_csgo', 'ArcticPanda'),
('surf_nocolors', 'N/A'),
('surf_nocturns_hopeless', 'Lownine^'),
('surf_nocturns_queen', 'Lownine^'),
('surf_nostromo_csgo', 'Horsefeathers'),
('surf_nothing', 'N/A'),
('surf_not_on', 'N/A'),
('surf_not_so_beginner', 'WALL-E'),
('surf_not_so_disaster', 'Mr.25'),
('surf_not_so_hentai', 'A-ha!'),
('surf_not_so_neb', 'JD!'),
('surf_not_so_quick', 'Sam'),
('surf_not_so_sinister', 'RambJoe'),
('surf_not_so_zen_fix', 'Mr.25'),
('surf_nova', 'KappaEliitti'),
('surf_noworth', 'Gttotchh'),
('surf_numbers', 'Gorange Ninja'),
('surf_numbers2', 'Granis'),
('surf_nyx', 'Syncronyze'),
('surf_nyze', 'Syncronyze'),
('surf_ny_advance_nsf_v2', 'FAJ'),
('surf_ny_aerial', 'N/A'),
('surf_ny_momentum2_ksf', 'FAJ'),
('surf_ny_momentum_v3_1', 'FAJ'),
('surf_ny_platinum', 'FAJ'),
('surf_ny_superhappiest_b3', 'FAJ'),
('surf_n_bhop_beta1', 'N/A'),
('surf_n_turf', 'ApeXe'),
('surf_oasis', 'Phurix'),
('surf_occur', 'Xtra_Festive'),
('surf_oddworld', 'Exxe'),
('surf_odyssey', 'RiddlerAJ'),
('surf_oejz_v2', 'Ale'),
('surf_offskill', 'KappaEliitti'),
('surf_olympics', 'THAY-imagine'),
('surf_olympus', 'FriendlyChemist'),
('surf_oma', 'Creatin'),
('surf_omnibus', 'SKAR'),
('surf_oompa2', 'Lody'),
('surf_oompa_loompa', 'CNCP'),
('surf_opus', 'Oui'),
('surf_orangewood', 'HannibalBy'),
('surf_orbion', 'Collaboration'),
('surf_organs', 'Incredirocks'),
('surf_original', 'Wayne3288'),
('surf_orion', 'N/A'),
('surf_ori_l', 'Stats33'),
('surf_orthodox_fix', 'ArcticPanda'),
('surf_our', 'not_a_zombie'),
('surf_overflight', 'Kirillins-'),
('surf_overgrowth', 'Fission'),
('surf_overgrowth2', 'Fission'),
('surf_paddy', 'Hardex'),
('surf_pagoda', 'PretzL'),
('surf_palace', 'N/A'),
('surf_palais', 'Xtra_Festive'),
('surf_palette_v2', 'Bravesurf'),
('surf_palikka_fix', 'N/A'),
('surf_palm', 'Xtra_Festive'),
('surf_pancake', 'Hardex'),
('surf_pandemonium_njv', 'Collaboration'),
('surf_pandora', 'Sonia'),
('surf_panono', 'Watri'),
('surf_pantheon', 'Garanimal'),
('surf_pantheon_beta', 'Garanimal'),
('surf_papertown', 'Sam'),
('surf_parachutes', 'ApeXe'),
('surf_paradigm', 'Pyllytonttu'),
('surf_paradise', 'Wiuuuh'),
('surf_paranoid_enigma', 'Paragon'),
('surf_parc_colore', 'Exither'),
('surf_parrot_selector', 'Ptad'),
('surf_pastel', 'G O O S'),
('surf_pathfinder', 'Xtra_Festive'),
('surf_pavilion', 'Black Sheep'),
('surf_peg_save38', 'N/A'),
('surf_peg_save38_fix', 'N/A'),
('surf_perennial', 'Granis '),
('surf_perforated_restored', 'Matteman'),
('surf_performance', 'Konstantinov'),
('surf_peruna', 'Microwave'),
('surf_petrus', 'iNooVa'),
('surf_petrus2', 'iNooVa'),
('surf_phantoml0rd_beta', 'Tioga060'),
('surf_phuli', 'Yush'),
('surf_physics', 'ColdAnimation'),
('surf_piano', 'ZiomekYOYO'),
('surf_pinkbash', 'Vay'),
('surf_pinkcubes_fix', 'YajiGod'),
('surf_pinkpiggy', 'N/A'),
('surf_pj_training1', 'Cirno'),
('surf_pj_training2', 'Cirno'),
('surf_placid', 'Enjooi'),
('surf_plaguelands_beta7a', 'Ryan S.'),
('surf_plaster', 'Tree'),
('surf_plastered', 'Toilet'),
('surf_platinum', 'FriendlyChemist'),
('surf_platypus', 'Platypushunter'),
('surf_plethora_fix', 'THAY-imagine'),
('surf_pls', 'Biji'),
('surf_pocari', 'Kingkurtis'),
('surf_pogomogo_b3', 'N/A'),
('surf_poke_b9', 'N/A'),
('surf_polonia', 'Collaboration'),
('surf_polski_sklep', 'Crystal'),
('surf_polygon', 'Diealready'),
('surf_polytron', 'Develo'),
('surf_porn_fix', 'Monkeywithagun'),
('surf_portal_easy_beta1', 'Kotton'),
('surf_portal_game4', 'N/A'),
('surf_potato', 'Moth'),
('surf_pox', 'Krusty'),
('surf_pox_revamp', 'Bocuma'),
('surf_prelude_ksf', 'God Damnit Nappa'),
('surf_premium', 'Maz64'),
('surf_presmon_fix', 'Arroba'),
('surf_primero_njv', 'Zee'),
('surf_prime_time_r3vamp', 'ZaLoS'),
('surf_princess', 'Kuiq'),
('surf_progress', 'Sam, Xtra_Festive'),
('surf_proliferation', 'Krealington'),
('surf_prolix', 'T3tra'),
('surf_prosaic_njv', 'T3tra'),
('surf_prosperity_v2', 'Fuddy'),
('surf_prosperous', 'Fuddy'),
('surf_proximity_final', 'Pand3mic'),
('surf_psi', 'Waffleburger'),
('surf_psi_fixed', 'Waffleburger'),
('surf_psychedelia', 'Sid'),
('surf_psycho_njv', 'HellRaisedSurfer'),
('surf_purdy', 'Somber'),
('surf_pure', 'N/A'),
('surf_purgatory', 'THAY-imagine'),
('surf_pyllyt1', 'TyöstöKärry'),
('surf_pyrism_njv', 'NotSmashed'),
('surf_pyzire', 'TaiKii'),
('surf_qlimax_q', 'Helix'),
('surf_quantum_njv', 'Sangre'),
('surf_quarantine', 'Collaboration'),
('surf_quark_rc', 'N/A'),
('surf_quartus_ksf', 'Juxtapo'),
('surf_quasar_njv', 'Rapsodia'),
('surf_quattro', 'N/A'),
('surf_queen_of_the_ween', 'Otter'),
('surf_quickie', 'Sam'),
('surf_quilavar', 'Helix'),
('surf_radiation_hazard', 'WarrioR^^'),
('surf_ragequit', 'Kiiru'),
('surf_ragu', 'Raafje'),
('surf_raidboss_beta2', 'Kotton'),
('surf_rainbow', 'Xenophenous'),
('surf_rainbow_adventure', 'Astro & Kmart Team Member'),
('surf_rampe', 'Activeed'),
('surf_rands_njv', 'Monkeywithagun'),
('surf_raphaello', 'Krealington'),
('surf_rapid_njv', 'Ch!ll3'),
('surf_raq', 'RAQ'),
('surf_raq2', 'RAQ'),
('surf_rat', 'Rathe'),
('surf_ravine_go', 'FriendlyChemist'),
('surf_razer_final', 'Compact'),
('surf_reactor_go', 'Kujoen'),
('surf_rebel_resistance_final4_swg', 'N/A'),
('surf_rebel_resistance_njv', 'Arcangel845'),
('surf_rebel_scaz_csgo', 'Scaz.zaf'),
('surf_reblis_final', 'Crystal'),
('surf_redemption_b1', 'Sangre'),
('surf_reflex', 'Cthulu'),
('surf_refraxis', 'ChiChiN'),
('surf_remeanian', 'FPS God'),
('surf_replicant', 'Spy Complex'),
('surf_reprise', 'TeMP'),
('surf_reprise_h', 'TeMP, Arxxy, Bocuma'),
('surf_republeague', 'BRNDMORE'),
('surf_research', 'Sacricx & Headshot'),
('surf_resort', 'WALL-E'),
('surf_resort_jk_fix', 'WALL-E'),
('surf_resource', 'Biji'),
('surf_restart', 'BOI'),
('surf_retroartz', 'Razersurf'),
('surf_retry', 'iodaN^'),
('surf_reveal', 'Saigar'),
('surf_revolution', 'Kahvo'),
('surf_reytx', 'Xtra_Festive'),
('surf_rez', 'Xbmann'),
('surf_rez2', 'Xbmann'),
('surf_rgb', 'Mrdeadguy34'),
('surf_ridge_tweets', 'Andrew'),
('surf_ripper', 'JackTheStripper'),
('surf_riva', 'R1vaa'),
('surf_road', 'Chmilk'),
('surf_road_to_hell', 'SkariZ^'),
('surf_rocco', 'FPS God'),
('surf_rocco_v2', 'FPS God'),
('surf_rolly', 'Klemix_RU'),
('surf_roman', 'Horsefeathers'),
('surf_rooftopsedge', 'Kingkurtis'),
('surf_rooftopsv2', 'Koga73'),
('surf_rookie2', 'Wiuuuh'),
('surf_rookie_fix', 'Kiiru'),
('surf_roomservice', 'GUINN355'),
('surf_roomservice_2', 'GUINN355'),
('surf_roomservice_3', 'GUINN355'),
('surf_rope', 'Nitropath'),
('surf_royal', 'Synx'),
('surf_royal_ez', 'N/A'),
('surf_rst', 'Synx'),
('surf_rstar', 'COUNTERWEIGHT'),
('surf_rtv_2', 'Ghost1648928'),
('surf_rubiks_cube', 'juvee'),
('surf_runewords', 'Biji'),
('surf_runewords2', 'Biji'),
('surf_runewords2_lod', 'Biji'),
('surf_runner', 'Koga73'),
('surf_rustic', 'Juxtapo'),
('surf_rustic_v2', 'Juxtapo'),
('surf_sacrifice', 'Spree'),
('surf_salient', 'Collaboration'),
('surf_salient2', 'Collaboration'),
('surf_salvador', 'iNooVa'),
('surf_salvation', 'Danger'),
('surf_salvia', 'Pires'),
('surf_sanctuary', 'Benchmarked'),
('surf_sandbrick', 'Vay, HypestaR'),
('surf_sanding', 'Compact'),
('surf_sandman', 'Sandman'),
('surf_sandman_v2', 'ArcticPanda'),
('surf_sandsmile', '★ Wingshot ★'),
('surf_sandstorm2', 'ArcticPanda'),
('surf_sandtrap', 'ArcticPanda'),
('surf_sandtrap2', 'ArcticPanda'),
('surf_sand_world', 'Marxes'),
('surf_sanguine', 'Krealington'),
('surf_sapiens', 'Legeshq'),
('surf_satellite_fix', 'Biji, iNooVa'),
('surf_saturday_fix', 'iamsupaman'),
('surf_savant_njv', 'Collaboration'),
('surf_saya', 'Kasumi ^3'),
('surf_SA_gao_v1', '#Fartshit'),
('surf_scarlet', 'PrisonNightmare'),
('surf_school_kzg', 'Sid'),
('surf_schwifty', 'Googee '),
('surf_scientist', 'ApeXe'),
('surf_sci_fi', 'Collaboration'),
('surf_scorch_go', 'Ver'),
('surf_scrub', 'Xen'),
('surf_sc_colours', 'sC'),
('surf_sc_essence_v2_njv', 'sC'),
('surf_se7en', 'SONICSOUR'),
('surf_seasons', 'N/A'),
('surf_seasons_fixed', 'God Damnit Nappa'),
('surf_seaworld_fix', 'Hulda'),
('surf_sea_horse_sea_hell', 'Novaki'),
('surf_secluded', 'PrisonNightmare'),
('surf_second', 'Not_a_zombie'),
('surf_selenka', 'DangerHSW'),
('surf_semesterbreak_fix', 'Sam'),
('surf_sempar_njv', 'Seme'),
('surf_sensation', 'Billy & Sangre'),
('surf_sensation_beta_v3', 'Kova'),
('surf_sentient', 'TeMP'),
('surf_sequoia', 'Maz64'),
('surf_seraph', 'Cyber'),
('surf_serenegarden', 'Ice Horison'),
('surf_serenity', 'Hardex'),
('surf_serenity2', 'Hardex'),
('surf_sewers', 'Monkeywithagun'),
('surf_sexellence2', 'Florida Man'),
('surf_sexplizooimed', 'Collaboration'),
('surf_sexyartz_njv', 'Razersurf'),
('surf_sh', 'Nano'),
('surf_shady', 'Sanguine'),
('surf_shady_h', 'Sanguine'),
('surf_shambles', 'Nmroxy'),
('surf_shit_v3', 'N/A'),
('surf_shodan', 'Spy Complex'),
('surf_shoria', 'Razersurf'),
('surf_shrug2', 'Shizangle'),
('surf_sideflick_v2', 'Oatneil'),
('surf_simple_v1b', 'N/A'),
('surf_simpsons_go_rc2', 'The-Goose'),
('surf_simpsons_refix', 'The-Goose'),
('surf_singletons_njv', 'AdamRH'),
('surf_sinister2', 'Collaboration'),
('surf_sinister_evil', 'RambJoe'),
('surf_sinsane2_fix', 'Not_a_zombie'),
('surf_sinsane_ez', 'Mbopferkuch'),
('surf_sinsane_ksf', 'b0at'),
('surf_sippysip', 'Syncronyze'),
('surf_sirius', 'Granis'),
('surf_si_fa', 'TempSo'),
('surf_skeelee', 'Skeeleetraver'),
('surf_sketchy', 'Gorange Ninja'),
('surf_skill8', 'Monkeywithagun'),
('surf_skill8_m', 'Monkeywithagun'),
('surf_skipalot', 'EICHHOERNCHEN'),
('surf_skyborn', 'Koga73'),
('surf_skyfall_final', 'Exxe'),
('surf_skyflow', 'ins-ane'),
('surf_skyscrapers', 'Noobre'),
('surf_sky_ages', 'Helix'),
('surf_slob', 'Sam'),
('surf_slob2', 'Sam'),
('surf_slobs', 'Sam'),
('surf_sluice2', 'Razersurf'),
('surf_sluice_final', 'Razersurf'),
('surf_smaragd', 'Collaboration'),
('surf_smezone', 'Francastor'),
('surf_smile_njv', 'Compact'),
('surf_smule', 'Smule'),
('surf_snowslide', 'JorisCeoen'),
('surf_sodacity', 'Kingkurtis'),
('surf_solace', 'Sam'),
('surf_something_serious', 'Inverted Moongoat'),
('surf_something_v1', 'Yvng Chester'),
('surf_soothe', 'Ndoman3807'),
('surf_sorbat', 'Kaliumsorbat'),
('surf_southpark_refix', 'CrookedK3ANO'),
('surf_spacejam', 'Juxtapo'),
('surf_spaces', 'Cpt. Hopi'),
('surf_spaceship_ksf', 'Darck'),
('surf_spacewalk', 'N/A'),
('surf_spectra', 'Hork'),
('surf_spectre', 'Rathe'),
('surf_spectrum_njv', 'SKAR'),
('surf_spike', 'Granis'),
('surf_spindrop', 'Olliembm'),
('surf_spindrop_hard', 'Olliembm'),
('surf_squarestyle', 'Jappedk'),
('surf_squirrelsonvacation', 'EICHHOERNCHEN'),
('surf_stagejuan_ksf', 'Inverted Moongoat'),
('surf_standard', 'Axelelele'),
('surf_starfire_csgo', 'Ver'),
('surf_stargaze_csgo', 'Ver'),
('surf_static', 'GodOwner'),
('surf_stepbystep', 'N/A'),
('surf_stick', 'M3rl1n'),
('surf_stickybutt_alpha', 'Roosta & Panzer'),
('surf_stitched', 'Masog'),
('surf_stoneage', 'b0at'),
('surf_stonework', 'Mr. Cow'),
('surf_stonework2', 'Mr. Cow'),
('surf_stonework3', 'Mr. Cow'),
('surf_stonework4', 'Mr. Cow'),
('surf_stonks', 'Hardex'),
('surf_strafe', 'Masog'),
('surf_strike', 'Spree'),
('surf_subway', 'PretzL'),
('surf_summer', 'Collaboration'),
('surf_summit', 'Phurix'),
('surf_sunday', 'iamsupaman'),
('surf_sundown_njv', 'Skittl35'),
('surf_sungam', 'N/A'),
('surf_sunnyhappylove', 'Streebree'),
('surf_sunset2', 'Exither'),
('surf_sunset_njv', 'Exither'),
('surf_sup', 'WALL-E'),
('surf_superbia', 'Seynethic'),
('surf_superbia_new', 'Seynethic'),
('surf_superduperm80s', 'PowerfulBacon'),
('surf_surfsup', 'N/A'),
('surf_surprise', 'Wiuuuh'),
('surf_swagtoast', 'WALL-E'),
('surf_sylvan', 'Sagan'),
('surf_symbiosis', 'Quensis'),
('surf_synada', 'Hesuka'),
('surf_syria', 'Razersurf'),
('surf_syria_again', 'Razersurf'),
('surf_systemlost_wr', 'N/A'),
('surf_s_t_a_t_i_o_n', 'Collaboration'),
('surf_tabasco', 'Rose'),
('surf_take1', 'Monkeywithagun'),
('surf_taq_njv', 'Monkeywithagun'),
('surf_technique', 'Xtra_Festive'),
('surf_teho_v1', 'Teho'),
('surf_telstar', 'Kompile'),
('surf_tempest', 'Hardex'),
('surf_tempest2', 'Hardex'),
('surf_temple_final', 'N/A'),
('surf_tenacious', 'Meowie'),
('surf_tendies', 'Granis'),
('surf_tensile_njv', 'Diealready'),
('surf_tensor', 'Superbike'),
('surf_tentacion', 'Crossdesu'),
('surf_tentacion_boo', 'Crossdesu'),
('surf_tenzo', 'Doggo'),
('surf_tequila', 'ApeXe'),
('surf_test', 'N/A'),
('surf_testerino', 'N/A'),
('surf_thatsneat', 'Big Daddy'),
('surf_the-hazard', 'N/A'),
('surf_thembrium_sns', 'Razersurf'),
('surf_theme', 'Phurix'),
('surf_thesteve', 'Eichhörnchen'),
('surf_the_distance', 'CollaborationA'),
('surf_the_forest', 'Jez'),
('surf_the_gloaming_rat', 'Roosta'),
('surf_the_lost_city', 'N/A'),
('surf_the_ofen', 'Ofen'),
('surf_the_unexpected', 'Eichhörnchen'),
('surf_the_web', 'Cuddly'),
('surf_the_web_v2', 'Cuddly'),
('surf_thicket', 'iNooVa'),
('surf_thief_fix', 'N/A'),
('surf_third4', 'Captain Haddock'),
('surf_this_njv', 'Bravesurf'),
('surf_this_time', 'Titty Sprinkles'),
('surf_timber', 'Kinder'),
('surf_timewarp', 'Tioga060'),
('surf_tioga060', 'Tioga060'),
('surf_togo', 'Jongent123'),
('surf_tomb_redone', 'N/A'),
('surf_toohard', 'N/A'),
('surf_toot', 'Tooticans'),
('surf_torque', 'Sangre'),
('surf_torque2_njv', 'Sangre'),
('surf_torrent_njv_fix', 'Egan'),
('surf_total_beginners_beta', 'Gorange'),
('surf_training', 'N/A'),
('surf_trainingschool', 'N/A'),
('surf_trance_ksf', 'UZY'),
('surf_tranquil', 'PrisonNightmare'),
('surf_tranquility', 'Young Pen Griffey'),
('surf_transient', 'Collaboration'),
('surf_trapped', 'ArcticPanda'),
('surf_trapped2', 'ArcticPanda'),
('surf_trash', 'Myldero'),
('surf_treasurehunt_go', 'The Frying Dutch Pan'),
('surf_treefort', 'Collaboration'),
('surf_treespam', 'Pand3mic'),
('surf_trial', 'N/A'),
('surf_tricky_chaos', 'N/A'),
('surf_triggered', 'Lody'),
('surf_trihard', 'Sjom7e'),
('surf_trinity', 'Der Geier'),
('surf_trippy', 'Stealthgerbil'),
('surf_tronia_njv', 'Sangre'),
('surf_tronic_njv', 'Sangre'),
('surf_tron_njv', 'PireS'),
('surf_tropical', 'N/A'),
('surf_trump_beta1', 'N/A'),
('surf_trump_rc1', 'N/A'),
('surf_truth', '64mb'),
('surf_tui_1', 'Tuitara'),
('surf_tundra', 'Malt'),
('surf_tundra_v2', 'Malt'),
('surf_tunnel', 'Sjup'),
('surf_turtle', 'Swaaaaag'),
('surf_tuscany_go', 'Exxe'),
('surf_tuxedo_csgo', 'Caksoso'),
('surf_twilight', 'God Damnit Nappa'),
('surf_two_colour', 'Maza51'),
('surf_tycho', 'TaiKii'),
('surf_ultimate', 'SpexiS'),
('surf_ultimatum', 'Godowner'),
('surf_underearth', 'Slasher/Hussa'),
('surf_underneath', 'MOKKAMASTER'),
('surf_underworld_go', 'Billy'),
('surf_unknown', 'Gorange Ninja'),
('surf_unnamed', 'Quark'),
('surf_unraveled', 'Spy Complex'),
('surf_unreal2', 'Hulda'),
('surf_unreal_njv', 'Hulda'),
('surf_unusual_njv', 'InC'),
('surf_upryzingx', 'N/A'),
('surf_urban', 'Gorange Ninja'),
('surf_utopia_night', 'Koga73'),
('surf_utopia_njv', 'Panzer'),
('surf_utopia_v3', 'Panzer'),
('surf_val', 'Val'),
('surf_vale', 'Xtra_Festive'),
('surf_vale2', 'Xtra_Festive'),
('surf_vale_fotg', 'Xtra_Festive'),
('surf_valpect', 'CRASHFORT'),
('surf_van', 'Saigar'),
('surf_vast', 'Krealington'),
('surf_vdl_training', 'N/A'),
('surf_vector_final', 'Lucky Charms'),
('surf_vegetables', 'Collaboration'),
('surf_velianglium', 'Konstantinov'),
('surf_velocity_nsf', 'Collaboration'),
('surf_vents', 'Forki'),
('surf_verge', 'N/A'),
('surf_vgaport_go', 'Flip, YajiGod, Unknown'),
('surf_vienna', 'ApeXe'),
('surf_violet', 'Zolfeca'),
('surf_vitun_rotta', 'TyostoKarry'),
('surf_volcanic', 'Spy Complex'),
('surf_volvic', 'iNooVa'),
('surf_wahey', 'Joeyy'),
('surf_warped', 'EICHHOERNCHEN'),
('surf_water-run_b5_fix', 'Mario & Nutz'),
('surf_water-run_banjo_skill', 'Mario & Nutz'),
('surf_waterworks', 'Skittl35'),
('surf_wazor', 'Collaboration'),
('surf_wew', 'Comrade Teammate'),
('surf_wexo', 'N/A'),
('surf_whiteout', 'Phurix'),
('surf_whitewall', 'N/A'),
('surf_whoknows', 'Malt'),
('surf_whoknows2', 'Malt'),
('surf_whoknows3', 'Malt'),
('surf_whynot', 'Juvee'),
('surf_wicked', 'Collaboration'),
('surf_willy1', 'Saigar'),
('surf_windrunner_final', 'Aust.Mon'),
('surf_wisdom', 'Watti'),
('surf_wizard', 'Biji'),
('surf_wolf_final', 'Thebman8794'),
('surf_woo', 'N/A'),
('surf_woodhouse', 'Wingshot'),
('surf_woodspec', 'Noxid'),
('surf_wood_fix', 'Enjooi & System Error'),
('surf_x', 'Helix'),
('surf_x2_beta07', 'N/A'),
('surf_xd', 'Granis'),
('surf_xeno', 'Apergios'),
('surf_xeno_v2_watermelon', 'Apergios'),
('surf_xiv_blood', 'SmOoth123'),
('surf_y', 'N/A'),
('surf_yaaan', 'N/A'),
('surf_yay', 'Hulda'),
('surf_year3000', 'Archangel'),
('surf_yeet', 'Twat'),
('surf_yellow', 'M_Lama'),
('surf_yiff', 'TheCosmicWolf'),
('surf_your_way', 'SkyppySDK'),
('surf_z', 'N/A'),
('surf_zbig2', 'Collaboration'),
('surf_zealand', 'XBMANN'),
('surf_zeitgeist', 'Spy Complex'),
('surf_zen', 'mr.25'),
('surf_zen2', 'mr.25'),
('surf_zenith', 'Sneakyyy'),
('surf_zen_fix', 'mr.25'),
('surf_zeonine_fix', 'Collaboration'),
('surf_zion_njv', 'N/A'),
('surf_zlash', 'shalz'),
('surf_zoomathon', 'Sid'),
('surf_zoomboys_csgo', 'Sid'),
('surf_zor', 'pretzL'),
('surf_ancient', 'The_Ancient_One'),
('surf_sos', 'Koga73'),
('surf_year3000_fix', 'Archangel'),
('surf_nuclear', 'SpyComplex'),
('surf_agony_go', 'Proxychains'),
('surf_scorpsground', 'Scorps'),
('surf_first_to_finish', 'Santa'),
('surf_wank', 'Deano'),
('surf_avfe2', 'N/A'),
('surf_dice_66_rc3_fix', 'N/A'),
('surf_ne_huiny', 'N/A');



CREATE TABLE ck_temp 
SELECT b.mapname, b.tier, b.maxvelocity, b.announcerecord, b.gravityfix, b.ranked, b.stages, b.bonuses, a.mapper
FROM ck_mapper AS a
RIGHT JOIN ck_maptier AS b
ON a.mapname = b.mapname;
ALTER TABLE ck_maptier
RENAME TO ck_maptier_backup;
ALTER TABLE ck_temp
RENAME TO ck_maptier;
ALTER TABLE `ck_maptier`
ADD PRIMARY KEY (`mapname`);
COMMIT;
DROP TABLE ck_mapper;